version: '3.9'

services:
  web:
    container_name: backend
    image: backend
    build:
      context: ./backend  
    ports:
      - 5000:5000
    env_file:
      - .env

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend 
    ports:
      - 3000:3000 
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000  

  db:
    container_name: database
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: ikSd1s7ElYPK
      POSTGRES_DB: prisma_migrate_shadow_db_6f421977-41e5-4059-996a-51843fb04e75
      DB_HOST: ep-old-wood-a58j3peg.us-east-2.aws.neon.tech
      DB_PORT: 5432
      DB_SSLMODE: require
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
